
config:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:
zeroconf:
discovery:
my:
energy:
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
# mqtt:
#   discovery: true
#   broker: 127.0.0.1
#   username: !secret username
#   password: !secret password

# zwave:
#   usb_path: /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_8130021D-if00-port0

homeassistant:
  customize: !include customize.yaml

person:
  - name: Joshua
    id: d047a30721db467aba5090eac39ef0f6
    user_id: 0deba9a5d55f4283a58721dd67e57107
    device_trackers:
      - device_tracker.joshua
      - device_tracker.pixel_5
     # - device_tracker.ping_joshua
  - name: Josie
    id: 679231f68a4d4e05b2a552cc84133a2c
    user_id: f3f546705e9844379edf982ea68104a8
    device_trackers:
      - device_tracker.josie
      - device_tracker.pixel_3a
      - device_tracker.ping_josie
  - name: Lia
    id: 058b429c295946dbbfcd4560b6a76c2e
    device_trackers:
      - device_tracker.lias_iphone_lan
  - name: Dad
    id: 5bef81ed9ba3422590d3b42ff265b91b
    device_trackers:
      - device_tracker.galaxy_s9_lan

zone: !include zones.yaml

tts:
  - platform: google_translate
    base_url: http://192.168.86.93:8123
  - platform: google_cloud
    key_file: Hassio-847c31d4c633.json
    language: en-US
    gender: female
    voice: en-US-Wavenet-F

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
frontend:
  themes: !include_dir_merge_named themes
  #extra_html_url:
  #  - /local/custom_ui/state-card-custom-ui.html
  #extra_html_url_es5:
  #  - /local/custom_ui/state-card-custom-ui-es5.html

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 192.168.86.93
    - 172.30.33.6
    - 172.30.33.7
    - 172.30.32.1
    - 172.30.33.4
#  base_url: !secret base_url
#  ssl_certificate: !secret ssl_cert
#  ssl_key: !secret ssl_key

wemo:
  discovery: true

spotcast:
  sp_dc: !secret spotify_username
  sp_key: !secret spotify_password

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

history:
  exclude:
    domains:
      - notify
      - persistent_notification
      - automation
    entities:
      - device_tracker.galaxy_s9_lan
      - device_tracker.joshua
      - device_tracker.josie
      - device_tracker.pixel_3
      - device_tracker.lias_iphone_lan
      - input_boolean.night_mode
      - input_boolean.running
      - input_boolean.vacation
      - input_boolean.joshua_sleeping

logbook:
  exclude:
    entities:
      - device_tracker.galaxy_s9_lan
      - device_tracker.joshua
      - device_tracker.josie
      - device_tracker.pixel_3
      - device_tracker.lias_iphone_lan
      - input_boolean.night_mode
      - input_boolean.running

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5
  exclude:
    domains:
      - calendar
      - weather
      - zone
      - automation
    entities:
      - sun.sun
      - sensor.dark_sky_icon
      - sensor.hacs
      - light.hue_white_lamp_4
      - light.hue_white_lamp_5
      - light.joshua_bedroom_light_1
      - light.joshua_bedroom_light_2
      - light.laundry_room_1
      - light.laundry_room_2
      - sensor.google_wifi_current_version
      - sensor.google_wifi_last_restart
      - sensor.google_wifi_local_ip
      - sensor.google_wifi_new_version
      - sensor.google_wifi_status
      - sensor.google_wifi_uptime
      - sensor.dark_sky_dew_point
      - sensor.dark_sky_dew_point_0d
      - sensor.dark_sky_dew_point_0h
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_0h
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_0h
      - sensor.dark_sky_temperature_0h
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_0h
      - input_boolean.joshua_home
      - input_boolean.josie_home
      - sensor.tv_muted
      - sensor.tv_volume
      - sensor.tv_source
      - sensor.time
      - sensor.adguard_dns_queries
      - sensor.adguard_dns_queries_blocked
      - sensor.adguard_parental_control_blocked
      - sensor.adguard_safe_browsing_blocked
      - sensor.adguard_safe_searches_enforced
      - switch.adguard_filtering
      - switch.adguard_parental_control
      - switch.adguard_protection
      - switch.adguard_safe_browsing
      - switch.adguard_safe_search
      - switch.schedule_joshua_bedroom_switch_morning
      - switch.schedule_joshua_bedroom_switch_night
      - switch.schedule_josie_bedroom_switch
      - switch.schedule_tree
      - sensor.pixel_5_last_notification
      - sensor.pixel_3a_proximity_sensor

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant:
  project_id: hassio-aca8d
  service_account: !include service_account.json
  expose_by_default: true
  report_state: true
  exposed_domains:
    - switch
    - light
    - scene
    - script
  entity_config:
    light.joshua_bedroom_light_1:
      expose: false
    light.joshua_bedroom_light_2:
      expose: false
    light.hue_white_lamp_4:
      expose: false
    light.hue_white_lamp_5:
      expose: false
    light.laundry_room_1:
      expose: false
    light.laundry_room_2:
      expose: false
    input_boolean.movie_mode:
      expose: true
    sensor.bedroom_sensor_temperature:
      expose: true
    media_player.lg_tv:
      expose: true
    switch.adguard_filtering:
      expose: false
    switch.adguard_safe_browsing:
      expose: false
    switch.adguard_parental_control:
      expose: false
    switch.adguard_safe_search:
      expose: false
    switch.schedule_joshua_bedroom_switch_morning:
      expose: false
    switch.schedule_joshua_bedroom_switch_night:
      expose: false
    switch.schedule_josie_bedroom_switch:
      expose: false
    switch.schedule_tree:
      expose: false
    

device_tracker:
#   - platform: nmap_tracker
#     hosts: 
#       - 192.168.86.92
#       - 192.168.86.114
#       - 192.168.86.127
#       - 192.168.86.128
# #     - 192.168.86.1/24
#     home_interval: 5
#     consider_home: 300
#     interval_seconds: 60
#     track_new_devices: false
#     exclude:
#     - 192.168.86.93
  - platform: ping
    hosts:
      ping_josie: 192.168.86.114
      ping_joshua: 192.168.86.92

weather:
  - platform: darksky
    name: Home
    api_key: !secret darksky_api_key
    scan_interval: '00:15'
    mode: daily

notify:
  - platform: html5
    name: home
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'
  - name: ga_broadcast
    platform: rest
    resource: http://127.0.0.1:5000/broadcast_message
  - platform: telegram
    name: telegram_joshua
    chat_id: 1563546300

template:
  - binary_sensor:
      - name: Dryer Running
        unique_id: dryer_running
        icon: >
          {% if is_state('binary_sensor.dryer_running', 'on') %}
            mdi:tumble-dryer
          {% else %}
            mdi:tumble-dryer-off
          {% endif %}
        state: "{{ states('binary_sensor.vibration_ias_zone') }}"
        delay_on: '0:04:00'
        delay_off: '0:02:00'
      - name: Keyboard
        unique_id: keyboard_on
        icon: mdi:piano
        #   {% if is_state('binary_sensor.keyboard', 'on') %}
        #     mdi:piano
        #   {% else %}
        #     mdi:piano-off
        #   {% endif %}
        state: "{{ states('sensor.keyboard_electrical_measurement')|float > 6 }}"
      - name: Washing Machine Running
        unique_id: washing_machine_running
        icon: >
          {% if is_state('binary_sensor.washing_machine_running', 'on') %}
            mdi:washing-machine
          {% else %}
            mdi:washing-machine-off
          {% endif %}
        state: "{{ states('sensor.washing_machine_plug_output')|float > 5 }}"
        delay_off: '0:02:00'
  - trigger:
      - platform: state
        entity_id: light.basement_lights
        to: 'on'
    binary_sensor:
      - name: basement lights turned on
        unique_id: basement_lights_lock
        state: "{{ is_state('light.basement_lights', 'on') }}"
        auto_off: '00:00:10'

sensor:
  - platform: time_date
    display_options:
      - 'time'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: network_in
        arg: wlan0
      - type: network_out
        arg: wlan0
      - type: load_5m
  - platform: google_wifi
    host: 192.168.86.1
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    scan_interval: 180
  - platform: template
    sensors:
      tv_muted:
        friendly_name: 'TV muted'
        value_template: "{{ is_state_attr('media_player.lg_tv', 'is_volume_muted', true) }}"
      tv_volume:
        friendly_name: 'TV volume'
        value_template: "{{ state_attr('media_player.lg_tv', 'volume_level') }}"
        unit_of_measurement: 'percent'
      tv_source:
        friendly_name: 'TV source'
        value_template: "{{ state_attr('media_player.lg_tv', 'source') }}"
      tv_app:
        friendly_name: 'TV App'
        value_template: "{{ state_attr('media_player.basement_tv', 'app_name') }}"
      update_version:
        friendly_name: 'Lastest Home Assistant Version'
        value_template: "{{ state_attr('binary_sensor.updater', 'newest_version') }}"
      basement_lights_brightness:
        friendly_name: 'Basement Lights Brightness'
        value_template: "{{ state_attr('light.basement_lights', 'brightness') }}"
      outside_temperature:
        friendly_name: 'Temperature'
        value_template: "{{ state_attr('weather.kstl_hourly', 'temperature') }}"
        unique_id: outside_temperature
  - platform: darksky
    api_key: !secret darksky_api_key
    scan_interval: '00:10'
    forecast:
      - 0
    hourly_forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed

binary_sensor:
  - platform: wyzesense
    device: '/dev/hidraw0'
  - platform: workday
    country: US
  - platform: command_line
    name: Check Config Log
    device_class: connectivity
    command: 'test -f "/share/check_config.txt" && echo "ON" || echo "OFF"'
  - platform: bayesian
    prior: 0.3
    probability_threshold: 0.7
    name: Basement Occupied
    observations:
      - entity_id: binary_sensor.wyze_basement_motion
        platform: state
        to_state: 'on'
        prob_given_true: 0.3
        prob_given_false: 0
      - entity_id: light.basement_lights
        platform: state
        to_state: 'on'
        prob_given_true: 0.7
        prob_given_false: 0.1
      - entity_id: binary_sensor.wyze_basement_door
        platform: state
        to_state: 'on'
        prob_given_true: 0.7
        prob_given_false: 0.5
      - entity_id: group.all_people
        platform: state
        to_state: 'home'
        prob_given_true: 1.0
        prob_given_false: 0.5
      - entity_id: media_player.basement_tv
        platform: state
        to_state: 'playing'
        prob_given_true: 0.05
        prob_given_false: 0

media_player:
  - platform: androidtv
    host: 192.168.86.95
    name: "Basement TV"
    adb_server_ip: 127.0.0.1
    adb_server_port: 5037

webostv:
  name: "LG TV"
  host: 192.168.86.47

input_datetime:
input_select:
input_number:
input_boolean:
  night_mode:
    name: Night Mode
  joshua_sleeping:
    name: Joshua Sleeping
  josie_sleeping:
    name: Josie Sleeping
  running:
    name: Running
  vacation:
    name: Vacation
  joshua_home:
    name: Joshua Home Status
  josie_home:
    name: Josie Home Status
  movie_mode:
    name: Movie Mode
  tv_toggle:
    name: TV Toggle

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 1563546300
