
config:
history:
logbook:
map:
mobile_app:
ssdp:
sun:
system_health:
updater:
zeroconf:
discovery:

homeassistant:
  customize: !include customize.yaml

person:
  - name: Joshua
    id: d047a30721db467aba5090eac39ef0f6
    user_id: 0deba9a5d55f4283a58721dd67e57107
    device_trackers:
      - device_tracker.joshua
      - device_tracker.pixel_3
  - name: Josie
    id: 679231f68a4d4e05b2a552cc84133a2c
    user_id: f3f546705e9844379edf982ea68104a8
    device_trackers:
      - device_tracker.josie
  - name: Lia
    id: 058b429c295946dbbfcd4560b6a76c2e
    device_trackers:
      - device_tracker.lias_iphone_lan
  - name: Dad
    id: 5bef81ed9ba3422590d3b42ff265b91b
    device_trackers:
      - device_tracker.galaxy_s9_lan

zone: !include zones.yaml

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html

http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

wemo:
  discovery: true

recorder:
  db_url: !secret mariadb_url
  purge_keep_days: 5
  purge_interval: 1
  exclude:
    entities:
      - sun.sun
      - weather.home
      - weather.home_2
      - sensor.dark_sky_icon
      - sensor.hacs

google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

google_assistant:
  project_id: hassio-aca8d
  api_key: !secret google_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light
    - scene
    - script
  entity_config:
    light.joshua_bedroom_light_1:
      expose: false
    light.joshua_bedroom_light_2:
      expose: false
    light.hue_white_lamp_4:
      expose: false
    light.hue_white_lamp_5:
      expose: false

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.1/24
    home_interval: 5
    consider_home: 120
    exclude:
     - 192.168.86.93

weather:
  - platform: darksky
    name: Home
    api_key: !secret darksky_api_key
    scan_interval: '00:15'
    mode: daily

notify:
  - platform: html5
    name: home
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email
  - name: slack
    platform: slack
    api_key: !secret slack_api_key
    default_channel: '#home'

sensor:
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    scan_interval: 180
  - platform: google_travel_time
    api_key: !secret google_maps_api_key
    origin: !secret home_place_id
    destination: !secret work_place_id
    scan_interval: 1800
  - platform: darksky
    api_key: !secret darksky_api_key
    scan_interval: '00:10'
    forecast:
      - 0
    hourly_forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature
      - dew_point
      - wind_speed

input_boolean:
  night_mode:
    name: Night Mode
  sleeping:
    name: Sleeping
  running:
    name: Running
  vacation:
    name: Vacation
