
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
homeassistant:
  customize: !include customize.yaml
frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

wemo:
  discovery: true

google_assistant:
  project_id: hassio-aca8d
  api_key: !secret google_api_key
  expose_by_default: true
  exposed_domains:
    - switch
    - light

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.86.1/24
    home_interval: 5
    exclude:
     - 192.168.86.93

weather:
  - platform: darksky
    name: Home
    api_key: !secret darksky_api_key
    scan_interval: '00:15'
    mode: daily

notify:
  - platform: html5
    name: home
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret email

sensor:
  - platform: google_travel_time
    api_key: !secret google_maps_api_key
    origin: !secret home_place_id
    destination: !secret work_place_id
    scan_interval: 1800

input_boolean:
  night_mode:
    name: Night Mode
    icon: mdi:theme-light-dark

shopping_list: