blank:
  color_type: blank-card
  styles:
    card:
      - width: 5px
      - height: 5px

filler:
  aspect_ratio: 1/1
  color-style: blank
  color_type: blank
  tap_action:
    action: none
  hold_action:
    action: none
  styles:
    card:
      - background-color: "rgba(0,0,0,0)"
      - box-shadow: none
      - border-radius: 20px
  color: rgba(0,0,0,0)

default:
  color: auto
  hold_action:
    action: more-info
  state:
    - id: 'off'
      styles:
        card:
          - filter: opacity(50%)
          - box-shadow: >-
              -5px -5px 8px 0 rgba(38, 41, 47,.5),5px 5px 8px 0 rgba(12, 13,
              15,.15)
        icon:
          - filter: grayscale(100%)
      value: 'off'
    - id: 'on'
      styles:
        card:
          - box-shadow: >-
              inset -4px -4px 10px 0 rgba(38, 41, 47,.5), inset 4px 4px 12px 0
              rgba(12, 13, 15,.3)
      value: 'on'
  styles:
    card:
      - width: 100px
      - height: 100px
      - box-shadow: >-
          -5px -5px 8px 0 rgba(38, 41, 47,.5),5px 5px 8px 0 rgba(12, 13,
          15,.15)
    label:
      - font-size: 15px
    name:
      - font-size: 15px
      - padding-bottom: 5px

media:
  double_tap_action:
    action: call-service
    service: media_player.toggle
    service_data:
      entity_id: '[[[ return entity.entity_id ]]]'
  entity_picture: '[[[ return entity.attributes.entity_picture; ]]]'
  hold_action:
    action: more-info
  label: '[[[ return entity.attributes.media_title ]]]'
  name: >-
    [[[ return entity.attributes.friendly_name.split(" ").slice(0,-1).join(" "); ]]]
  show_entity_picture: true
  show_label: true
  state:
    - styles:
        card:
          - filter: opacity(75%)
        icon:
          - filter: grayscale(30%)
      value: paused
    - id: 'off'
      styles:
        grid:
          - grid-template-areas: '"i" "n"'
          - grid-template-rows: null
          - grid-template-columns: null
      value: 'off'
    - id: idle
      styles:
        grid:
          - grid-template-areas: '"i" "n"'
          - grid-template-rows: null
          - grid-template-columns: null
      value: idle
  styles:
    grid:
      - grid-template-areas: '"i i i i" ". l l ." "n n n n"'
      - grid-template-rows: 3fr 1fr 1fr
      - grid-template-columns: 5% 1fr 1fr 5%
  tap_action:
    action: call-service
    service: |
      [[[
        if(entity.state == "off" || entity.state == "idle")
          return "media_player.toggle";
        else
          return "media_player.media_play_pause";
      ]]]
    service_data:
      entity_id: '[[[ return entity.entity_id ]]]'
  template: default

sensor:
  name: |
    [[[
      if (entity.attributes.unit_of_measurement != undefined)
        return entity.state + " " + entity.attributes.unit_of_measurement;
      else
        return entity.state;
    ]]]
  show_icon: false
  styles:
    name:
      - font-size: 22px
      - padding-bottom: 0px
  tap_action:
    action: more-info
  template: default

